version: '3.8'

services:
  food-management-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-management-app
    ports:
      - "8080:8080"
    restart: unless-stopped
