spring.application.name=demo

server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://isha2005:2005_isha@cluster0.vegaggl.mongodb.net/FoodDB}
spring.data.mongodb.database=FoodDB